---
title: Termine
---


# Termine 1 und 2

*27. und 29. Februar 2024*

Einstieg in das Syntax und die Datentypen in **R**, inklusive eine Einführung in
die Nutzung von **RStudio**.

- [Foliensatz Termin 1](Dateien/FolienRKurs-1.pdf)
- [Foliensatz Termin 2](Dateien/FolienRKurs-2.pdf)
- [Skript Tag 1](Dateien/Tag1.R)
- [Skript Tag 2](Dateien/Tag2.R)


# Termine 3 und 4

*05. und 07. März 2024*

Einführung in R-Objekten mit einer besonderen Berücksichtigung von Datensätzen
(Klasse `data.frame`), sowie das Schreiben und Lesen von Dateien.

- [Skript Tag 3](Dateien/Tag3.R)
- [Skript Tag 4](Dateien/Tag4.R)


# Termine 5 und 6

*12. und 14. März 2024*

Statistische Auswertungen von Datensätzen (Klasse `data.frame`) und Erstellung von Graphiken (Plots). Dazu werden bewährte Verfahren für Datenverwaltung diskutiert.
In dieser Version des Kurses wurde das Programmieren mit künstlicher Intelligenz als spezielles Thema eingeführt.

- [Foliensatz Programmieren mit KI](Dateien/Programmieren-mit-KI.pdf)
  - [Taschenrechner V1](Dateien/Taschenrechner_V1.R)
  - [Taschenrechner V2](Dateien/Taschenrechner_V2.R)
  - [Fiktive Daten](Dateien/FiktiveDaten.R)
- [Skript Tag 5](Dateien/Tag5.R)
- [Skript Tag 6](Dateien/Tag6.R)


# Termine 7 und 8

*19. und 21. März 2024*

Zweite Runde mit Plots, diesmal handeln wir Funktionen vom Paket `ggplot2`.
Automatisieren von Skripte mittels Schleifen, Funktionen und Quellcode.
Nach der letzten Sitzung bist du kein Anfänger mehr.
Zwei besondere Themen werden hier eine Einführung in Rmarkdown und eine Einführung in geographische Informationssystheme.

- [Folien Rmarkdown](Dateien/rmarkdown-intro.pdf)
  - [Rmarkdown Dokument](Dateien/document-1.Rmd)
- [Skript Tag 7](Dateien/Tag7.R)
- [Folien GIS](Dateien/gis-intro.pdf)
